apiVersion: apps/v1
kind: Deployment
metadata:
  name: goclone-v1
  namespace: goclone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goclone
      version: v1
  template:
    metadata:
      labels:
        app: goclone
        version: v1
        istio: monitor
    spec:
      containers:
        - name: goclone
          image: evanjd711/goclone:1.0.2
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: VCENTER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: goclone-secret
                  key: username
            - name: VCENTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: goclone-secret
                  key: password
          envFrom:
            - configMapRef:
                name: goclone-config
