apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: goclone-virtual-svc
  namespace: goclone
spec:
  hosts:
  - goclone.sdc.cpp
  gateways:
  - goclone-gateway
  http:
  - name: "goclone-v1-routes"
    match:
    - uri:
        prefix: /api/v1/
    route:
    - destination:
        port:
          number: 8080
        host: goclone-svc
        subset: v1
  - name: "goclone-v2-routes"
    match:
    - uri:
        prefix: /api/v2/
    route:
    - destination:
        port:
          number: 8080
        host: goclone-svc
        subset: v2
