name: Test Goclone

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

#on:
#  push:
#    branches:
#      - development
jobs:
  test:
    runs-on: [self-hosted]
    environment: Goclone
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.3

      - name: Run tests
        shell: bash
        env:
          LDAP_BIND_PASSWORD: ${{ secrets.LDAP_BIND_PASSWORD }}
          VCENTER_PASSWORD: ${{ secrets.VCENTER_PASSWORD }}
          VCENTER_USERNAME: ${{ secrets.VCENTER_USERNAME }}
        run: |
          source .env
          go mod tidy
          go test -v ./...
